services:
  postgres:
    image: postgres:16-alpine
    container_name: agendya-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: agendya
      POSTGRES_PASSWORD: agendya_dev_password
      POSTGRES_DB: agendya_dev
    ports:
      - '5433:5432'
    volumes:
      - agendya_postgres_data:/var/lib/postgresql/data

volumes:
  agendya_postgres_data:
